### ISSUE TITLE
/var/task/bin/pdftk: Permission denied

### ISSUE THREAD

**Issue by chehmer** [lob/lambda-pdftk-example#1]
Hey,

I got an error while trying to test the example function after uploaded it to Lambda from S3.
this is the error that I get: 
{
  "errorMessage": "Command failed: /bin/sh: /var/task/bin/pdftk: Permission denied\n",
  "errorType": "Error",
  "stackTrace": [
    "",
    "ChildProcess.exithandler (child_process.js:658:15)",
    "ChildProcess.emit (events.js:98:17)",
    "maybeClose (child_process.js:766:16)",
    "Socket.<anonymous> (child_process.js:979:11)",
    "Socket.emit (events.js:95:17)",
    "Pipe.close (net.js:466:12)"
  ]
}

configurations : 
IAM Role - lambda_basic_exectution : 
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "arn:aws:logs:_:_:*"
    }
  ]
}

I gave full permissions (chmod 777) to each file in the zip archive before uploading it to S3
What did I missed ?

**Comment by chehmer** [comment]
I fixed it by adding permission to the files in the bin folder...

**Comment by misantronic** [comment]
I had the same problem. Fixed it by `chmod +x pdftk`
