### ISSUE TITLE
How to use/test on AWS Lambda?

### ISSUE THREAD

**Issue by sabliao** [lob/lambda-pdftk-example#5]
I uploaded the zip file, but afterwards received the warning: "The deployment package of your Lambda function "pdftk" is too large to enable inline code editing. However, you can still invoke your function." *pdftk is what I named the lambda function

I decided to at least 'test' it by pressing the test button and going w/ their default event (since I thought it wouldn't matter what we passed to it), but that failed w/ the output:
`{
  "errorMessage": "2020-01-18T00:05:36.522Z e8312ad1-165e-4255-a5d9-6b5c50b374f8 Task timed out after 3.00 seconds"
}`

I thought the example was supposed to be a straightforward way to test a simple run of pdftk in lambda, but I don't know where I might've misunderstood/missed a step.

**Comment by stephenstilwell** [comment]
Did you ever fix your issue?

**Comment by sabliao** [comment]
@stephenstilwell It's been a while, but I don't think I did. Sorry if you were looking for help.
